import tkinter as tk
from tkinter import ttk
from config import *
import datetime
from dateutil.relativedelta import relativedelta

class RecurringMixin:
    def process_recurring_transactions(self):
        rules = _ld("recurring")
        if not rules: return
        
        trans = _ld("transactions")
        modified = False
        
        today_date = datetime.datetime.strptime(today(), "%Y-%m-%d").date()
        
        for rule in rules:
            if not rule.get("active", True): continue
            
            try:
                nxt = datetime.datetime.strptime(rule["next_date"], "%Y-%m-%d").date()
            except:
                continue
                
            while nxt <= today_date:
                # Generate transaction
                trans.append({
                    "id": mk_id(),
                    "type": rule["type"],
                    "date": nxt.strftime("%Y-%m-%d"),
                    "month": nxt.strftime("%Y-%m"),
                    "desc": rule["desc"] + " (Auto)",
                    "category": rule["category"],
                    "amount": rule["amount"],
                    "currency": rule.get("currency", "INR"),
                    "notes": "Generated by recurring rule."
                })
                modified = True
                
                # Advance next date
                freq = rule["frequency"]
                if freq == "Daily":
                    nxt += datetime.timedelta(days=1)
                elif freq == "Weekly":
                    nxt += datetime.timedelta(weeks=1)
                elif freq == "Monthly":
                    nxt += relativedelta(months=1)
                elif freq == "Quarterly":
                    nxt += relativedelta(months=3)
                elif freq == "Yearly":
                    nxt += relativedelta(years=1)
                else:
                    nxt += relativedelta(months=1) # Default to monthly fallback
                    
            rule["next_date"] = nxt.strftime("%Y-%m-%d")
            
        if modified:
            _sv("transactions", trans)
            _sv("recurring", rules)
            self._auto_notif() # trigger budget alerts if needed

    def show_recurring(self):
        self._set_nav("Recurring")
        self._set_title("Recurring Transactions")
        self._clear()

        f = self._scrollable(self._active_page_frame)
        
        rules = _ld("recurring")
        
        hdr = tk.Frame(f, bg=BG)
        hdr.pack(fill="x", padx=20, pady=15)
        tk.Label(hdr, text="Automate your fixed income and expenses", font=("Segoe UI", 11), bg=BG, fg=TS).pack(side="left")
        
        def _edit():
            sel = tv.selection()
            if not sel: return tk.messagebox.showwarning("Select", "Please select a rule to edit.")
            rec_id = str(sel[0])
            rec = next((r for r in _ld("recurring") if r["id"] == rec_id), None)
            if rec:
                self._add_recurring(rec)

        def _del():
            sel = tv.selection()
            if not sel: return
            if tk.messagebox.askyesno("Confirm", "Delete this recurring rule?\nGenerated transactions will not be deleted."):
                rec_id = str(sel[0])
                recs = [r for r in _ld("recurring") if r["id"] != rec_id]
                _sv("recurring", recs)
                self.show_recurring()
                tk.messagebox.showinfo("Deleted", "Rule deleted successfully.")
        
        self._tb_btn(hdr, "+ Add Rule", self._add_recurring)
        self._tb_btn(hdr, "✏  Edit", _edit, CB2)
        self._tb_btn(hdr, "🗑  Delete", _del, CB2)
        
        tv_f, tv = self._tv(f, ("ID", "Type", "Category", "Description", "Amount", "Frequency", "Next Date", "Status"), 
                           widths=[0, 80, 120, 200, 100, 100, 100, 80], height=15)
        tv.column("ID", width=0, stretch=False)
        tv_f.pack(fill="both", expand=True, padx=20, pady=(10, 20))
        
        rows = []
        for r in rules:
            amt = fmt_amt(r["amount"], r.get("currency", "INR"))
            status = "Active" if r.get("active", True) else "Paused"
            rows.append((r["id"], r["type"], r["category"], r["desc"], amt, r["frequency"], r["next_date"], status))
            
        self._tv_fill(tv, rows)
        
        def _on_double_click(e):
            sel = tv.selection()
            if not sel: return
            rec_id = str(sel[0])
            rec = next((r for r in _ld("recurring") if r["id"] == rec_id), None)
            if rec:
                self._add_recurring(rec)
        tv.bind("<Double-1>", _on_double_click)

    def _add_recurring(self, existing=None):
        defaults = existing or {}
        fields = [
            {"lbl": "Type", "k": "type", "type": "combo", "opts": ["expense", "income"]},
            {"lbl": "Frequency", "k": "frequency", "type": "combo", "opts": ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly"]},
            {"lbl": "Category", "k": "category", "type": "combo", "opts": EXPENSE_CATS + INCOME_CATS},
            {"lbl": "Description", "k": "desc", "type": "text"},
            {"lbl": f"Amount ({GLOBAL_STATE['display_currency']})", "k": "amount", "type": "text"},
            {"lbl": "Start/Next Date (YYYY-MM-DD)", "k": "next_date", "type": "text"},
            {"lbl": "Status (Active/Paused)", "k": "status", "type": "combo", "opts": ["Active", "Paused"]}
        ]
        
        if "next_date" not in defaults:
            defaults["next_date"] = today()
        if "status" not in defaults:
            defaults["status"] = "Active" if defaults.get("active", True) else "Paused"
            
        def _save(vals, dlg):
            if not vals["desc"].strip():
                return tk.messagebox.showerror("Error", "Description cannot be empty.")
                
            try: amt = float(vals["amount"])
            except: return tk.messagebox.showerror("Error", "Amount must be a number.")
            
            if amt < 0:
                return tk.messagebox.showerror("Error", "Amount cannot be negative.")
                
            if vals["frequency"] not in ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly"]:
                return tk.messagebox.showerror("Error", "Invalid frequency.")
            
            # Simple date validation
            try: datetime.datetime.strptime(vals["next_date"], "%Y-%m-%d")
            except: return tk.messagebox.showerror("Error", "Invalid date format. Use YYYY-MM-DD.")
            
            recs = _ld("recurring")
            
            # Duplicate check
            for r in recs:
                if r.get("desc") == vals["desc"] and r.get("amount") == amt and r.get("frequency") == vals["frequency"]:
                    if not existing or existing["id"] != r["id"]:
                        return tk.messagebox.showerror("Error", "A duplicate recurring rule already exists.")
            
            is_active = (vals["status"] == "Active")
            
            if existing:
                for r in recs:
                    if r["id"] == existing["id"]:
                        r.update({
                            "type": vals["type"],
                            "frequency": vals["frequency"],
                            "category": vals["category"],
                            "desc": vals["desc"],
                            "amount": amt,
                            "next_date": vals["next_date"],
                            "active": is_active
                        })
            else:
                recs.append({
                    "id": mk_id(),
                    "type": vals["type"],
                    "frequency": vals["frequency"],
                    "category": vals["category"],
                    "desc": vals["desc"],
                    "amount": amt,
                    "currency": GLOBAL_STATE["display_currency"],
                    "next_date": vals["next_date"],
                    "active": is_active
                })
            _sv("recurring", recs)
            dlg.destroy()
            self.show_recurring()

        self._dialog("Add/Edit Recurring Rule", fields, _save, defaults)
